const swipper=new Swiper(".swiper",{
    autoplay:{delay:3000},
    effect:"swip",
    loop:true,
    pagination:{
        el:".swiper-pagination"
    },
    navigation:{
        nextEl:".swiper-button-next",
        prevEl:".swiper-button-prev"
    },
    scrollbar:{
        el:"swiper-scrollbar"
    }
});


window.sr=ScrollReveal({reset:true});
     sr.reveal(".head1",{
         duration:1000,
         origin:"left",
         distance:"15%"
     });
     sr.reveal(".searbox",{
         duration:1000,
         origin:"bottom",
         distance:"15%",
         delay:500
     });
     sr.reveal("#carimg",{
         duration:200,
         distance:"10%",
         origin:"right",
         delay:500
     });
     sr.reveal(".car1",{
         duration:1000,
         distance:"10%",
         origin:"bottom",
         delay:500
     });
     sr.reveal(".car2",{
         duration:1000,
         distance:"10%",
         origin:"bottom",
         delay:1000
     });
     sr.reveal(".car3",{
         duration:1000,
         distance:"10%",
         origin:"bottom",
         delay:1500
     });
     sr.reveal(".car4",{
         duration:1000,
         distance:"10%",
         origin:"bottom",
         delay:2000
     });
     sr.reveal("#find",{
         duration:1000,
         distance:"10%",
         origin:"bottom",
         delay:500
     });
     sr.reveal("#dis",{
         duration:1000,
         distance:"15%",
         origin:"bottom",
         delay:500
     });
     sr.reveal("#findl",{
         duration:1000,
         distance:"20%",
         origin:"bottom",
         delay:500
     });
     sr.reveal("#location",{
         duration:1000,
         distance:"15%",
         origin:"right",
         delay:500
     });
     sr.reveal("#carda1",{
         duration:1000,
         distance:"20%",
         origin:"bottom",
         delay:500
     });
     sr.reveal("#carda2",{
         duration:1000,
         distance:"20%",
         origin:"bottom",
         delay:800
     });
     sr.reveal("#carda3",{
         duration:1000,
         distance:"20%",
         origin:"bottom",
         delay:1100
     });
     sr.reveal("#precr",{
         duration:1000,
         distance:"100%",
         origin:"bottom",
         delay:100
     });
     sr.reveal("#gio",{
         duration:1000,
         distance:"150%",
         origin:"bottom",
         delay:200
     });
     sr.reveal("#phn",{
         duration:1000,
         distance:"20%",
         origin:"right",
         delay:200
     });

     var ccar1=document.getElementById("ccar1");
     ccar1.addEventListener("click",()=>{
       console.log("hello");
     });
